map $http_user_agent $is_probe { default 0; ~kube-probe 1; }
map $status $is_error { default 0; ~^[45] 1; }
map "$is_probe:$is_error" $log_probe_fail { default 0; "1:1" 1; }
map $is_probe $not_probe { 0 1; 1 0; }

log_format json escape=json
  '{'
    '"ts":"$time_iso8601",'
    '"remote":"$remote_addr",'
    '"method":"$request_method",'
    '"uri":"$request_uri",'
    '"status":$status,'
    '"bytes":$body_bytes_sent,'
    '"rt":$request_time,'
    '"ref":"$http_referer",'
    '"ua":"$http_user_agent",'
    '"req_id":"$request_id"'
  '}';

log_format probe '$remote_addr - $time_local "$request" $status rt=$request_time';

error_log /dev/stderr warn;

server {
  listen 8080;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;
  gzip_static on;
  gzip_vary on;

  absolute_redirect off;
  port_in_redirect off;
  server_name_in_redirect off;

  access_log /dev/stdout json  if=$not_probe;
  access_log /dev/stdout probe if=$log_probe_fail;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location = /healthz {
    access_log off;
    add_header Content-Type application/json;
    return 200 '{"status":"HEALTHY"}';
  }

  location = /healthz/startup {
    access_log off;
    add_header Content-Type application/json;
    return 200 '{"status":"STARTUP_OK"}';
  }

  location = /healthz/ready {
    access_log off;
    add_header Content-Type application/json;
    return 200 '{"status":"READY_OK"}';
  }

  sendfile on;
  keepalive_timeout 65s;
}
